In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
a1 = np.random.random((3,3,3))
print(a1.shape)
print(a1)

(3, 3, 3)
[[[0.12315264 0.95368852 0.05008973]
  [0.26127348 0.96483791 0.02673053]
  [0.64940321 0.47795381 0.90454881]]

 [[0.49785523 0.1990452  0.37200669]
  [0.56354053 0.80604786 0.47793995]
  [0.66634268 0.66618531 0.67461855]]

 [[0.13716307 0.34958048 0.60859842]
  [0.02822074 0.0517652  0.5357471 ]
  [0.59718367 0.31872664 0.35157609]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a2 = np.diag(np.arange(4)+1,-1)
print(a2.shape)
print(a2)

(5, 5)
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
a3 = np.zeros((8,8),dtype=int)
a3[1::2,::2] = 1
a3[::2,1::2] = 1
print(a3)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
a4 = np.random.random((5,5))
print("Shape of a4 is : ",a4.shape)
print("Random matrix of 5x5 :\n\n",a4)
print("\n\nMean of a4: ",a4.mean(),"\nStandrand divion of a4: ", a4.std(),"\n\n")
print("Normalize a 5x5 random matrix\n\n")
print((a4-a4.mean())/a4.std())

Shape of a4 is :  (5, 5)
Random matrix of 5x5 :

 [[0.7344501  0.78862514 0.25970417 0.4483559  0.19904071]
 [0.15860758 0.67430687 0.86242232 0.99163714 0.01295498]
 [0.40753591 0.35815185 0.19895136 0.06791621 0.2540851 ]
 [0.98044233 0.30976998 0.36169815 0.37850759 0.86133129]
 [0.39393564 0.39923412 0.00877943 0.74118025 0.49804062]]


Mean of a4:  0.45398658939639885 
Standrand divion of a4:  0.2906772952568989 


Normalize a 5x5 random matrix


[[ 0.96486211  1.15123733 -0.66837837 -0.01937092 -0.8770753 ]
 [-1.01617502  0.7579549   1.40511743  1.84964755 -1.51725512]
 [-0.15980154 -0.32969463 -0.8773827  -1.32817523 -0.68770933]
 [ 1.81113471 -0.49613993 -0.3174945  -0.25966597  1.40136402]
 [-0.20658974 -0.1883617  -1.53162     0.98801546  0.1515565 ]]


# 5.  How to find common values between two arrays?

In [6]:
# np.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)[source]
# intersect1d takes arrays as input and gives another array as output which contain all the common values 
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print('common values between two arrays')
print(np.intersect1d(Z1,Z2))

[5 5 4 8 6 4 2 0 1 9]
[9 5 7 7 9 0 7 2 3 4]
common values between two arrays
[0 2 4 5 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday" ,yesterday)
print("today",today)
print("tomorrow",tomorrow)

yesterday 2020-07-25
today 2020-07-26
tomorrow 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [8]:
A = np.random.randint(0,5,5)
B = np.random.randint(0,5,5)
print(A)
print(B)
equal = np.array_equal(A,B)
print(equal)

[1 4 4 0 0]
[1 3 0 2 4]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
Z = np.random.random(10)
print(Z)
#Return indices of the maximum value
print(Z.argmax())
Z[Z.argmax()] = 0
print(Z)

[0.1418963  0.69146478 0.78212661 0.25088427 0.97624347 0.27350574
 0.82989788 0.01475097 0.1792859  0.44257695]
4
[0.1418963  0.69146478 0.78212661 0.25088427 0.         0.27350574
 0.82989788 0.01475097 0.1792859  0.44257695]


# 9. How to print all the values of an array?

In [10]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((5,5)) 
#print(Z[list(iter(list(range(0,5))))])
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [11]:
X = np.array([[1, 2], [4, 3]])
print(X) 
Y = X - X.mean(axis=1, keepdims=True)
print(Y) 

[[1 2]
 [4 3]]
[[-0.5  0.5]
 [ 0.5 -0.5]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
 
Z = np.ones(10)
print(Z) 
I =[1,3,5,7,9,1]
print(I) 
np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1, 3, 5, 7, 9, 1]
[1. 3. 1. 2. 1. 2. 1. 2. 1. 2.]


# 12.How to get the diagonal of a dot product?

In [13]:
 
A = np.array([[1, 2], [4, 3]])
B = np.array([[1, 2], [4, 3]])
print(A)
print(B)

np.diag(np.dot(A, B))

[[1 2]
 [4 3]]
[[1 2]
 [4 3]]


array([ 9, 17])

# 13.How to find the most frequent value in an array?

In [14]:
Z = np.random.randint(0,10,10)
print(Z)
from scipy import stats
a,b =stats.mode(Z)
print(a)
print(np.bincount(Z).argmax())

[6 9 6 8 0 8 6 6 4 9]
[6]
6


# 14.How to get the n largest values of an array

In [15]:
Z = np.arange(100)
print(Z)
np.random.shuffle(Z)
print(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[26 93 13 82 54 40 66 48 41 22  7 69 27  1  3 31 79  9 72 45 83 92 32 28
 75 16 29 46 88 19 84 78 73 33  8 70 60 99 36 61 47 21 64  2 42 96 24 91
 14 59 25 86 37 53 35 17 43 95 50 76 52 34 77  5  6 39 65 38 10 62 68 58
 90  4 56 81 55 12 51 57 94 30 97 63 89 20 80 85 49 71 18 74 87 44  0 67
 98 23 15 11]
[95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [16]:
Z = np.array([(1,2,3),
              (4,5,6)])
print(Z.T)
R = np.core.records.fromarrays(Z.T)
                              
print(R)

[[1 4]
 [2 5]
 [3 6]]
[(1, 2, 3) (4, 5, 6)]
