In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle 
# pickle is used to save the model created by us

In [3]:
df = pd.read_csv("hiring.csv")
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [4]:
df.isna().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [5]:
# experience

df['experience'].fillna(0, inplace=True)

In [6]:
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [7]:
df['test_score'].mean()

7.857142857142857

In [8]:
df['test_score'].fillna(df['test_score'].mean(), inplace=True)

In [9]:
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

__Dataset is Clean now.__

In [10]:
df.head()

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [11]:
X = df.iloc[:,:-1]

In [12]:
X.head()

experience  test_score  interview_score
0          0         8.0                9
1          0         8.0                6
2       five         6.0                7
3        two        10.0               10
4      seven         9.0                6

In [13]:
X.shape

(8, 3)

In [14]:
X.experience

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [15]:
# Convert text in the cols to integer values

def conv(x):
    dict = {'two':2, 'three':3, 'five':5, 'seven':7, 'ten':10, 0:0, 'eleven':11 }
    return dict[x]

In [16]:
X['experience'] = X['experience'].apply(lambda x: conv(x))

In [17]:
X.head()

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6

In [18]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       8 non-null      int64  
 1   test_score       8 non-null      float64
 2   interview_score  8 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 320.0 bytes


__X is ready.__

In [19]:
y = df.iloc[:,-1]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

I am not going to do traintestsplit as the dataset itself is very small.

However, you all are encouraged to do it later as a part of practice and submit it as an assignment.

__Q. You can select any of the projects covered till now  by any of the trainers and deploy the same.__

In [20]:
# Modeling

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [21]:
# Fit the model
lr.fit(X, y)

LinearRegression()

In [22]:
# Prediction Phase
y_pred=lr.predict(X)
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [23]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [24]:
from sklearn.metrics import r2_score
r2_score(y_pred, y)

0.9626511210293307

In [25]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [26]:
lr.predict([[3,9,7]])

array([58315.5019167])

In [27]:
lr.predict([[10,10,10]])

array([86612.80419155])

In [28]:
lr.predict([[10,2,3]])

array([55930.47274854])

# Model Deployment

In [29]:
# Here, we will save the 'lr' model to disk as 'model.py'

import pickle

pickle.dump(lr,open('model.pkl','wb'))
# Dump this model by the name "model.py" in the systems HDD and while doing this
# write this file using "write bytes" mode.

In [30]:
# Lets now try to load the same model by reading it from the system
# and using it for prediction

model2 = pickle.load(open("model.pkl","rb"))

In [31]:
model2.predict([[3,9,7]])

array([58315.5019167])

In [32]:
model2.predict([[10,10,10]])

array([86612.80419155])

In [33]:
model2.predict([[10,2,3]])

array([55930.47274854])

# Happy Learning