In [46]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import math

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df1 = df.drop(['PassengerId', 'Cabin', 'Ticket', 'Name'], axis = 1)
df1.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [5]:
le = preprocessing.LabelEncoder()
df1['Sex'] = le.fit_transform(df1['Sex'])
df1['Embarked'] = le.fit_transform(df1['Embarked'])

In [75]:
def my_func(dv):
    llist = df1.columns.to_list()
    llist.remove(dv)
    print('Dependent Variable:', dv)
    print('\nIndependent Variables:', *llist)
    y = df1[dv]
    X = df1.drop([dv], axis = 1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)
    clf = BernoulliNB()
    y_pred = clf.fit(X_train, y_train).predict(X_test)
    print(f'\n\nThe accuracy of the model for predicting "{dv}" for unseen data is {round(accuracy_score(y_test, y_pred, normalize=True)*100, 2)}%')
    print('\nConfusion matrix:\n', confusion_matrix(y_test, y_pred))
    

# DV - Survived

In [76]:
my_func('Survived')

Dependent Variable: Survived

Independent Variables: Pclass Sex Age SibSp Parch Fare Embarked


The accuracy of the model for predicting "Survived" for unseen data is 77.15%

Confusion matrix:
 [[131  26]
 [ 35  75]]


# DV - Passenger Class

In [77]:
my_func('Pclass')

Dependent Variable: Pclass

Independent Variables: Survived Sex Age SibSp Parch Fare Embarked


The accuracy of the model for predicting "Pclass" for unseen data is 59.18%

Confusion matrix:
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]


# DV - Gender

In [78]:
my_func('Sex')

Dependent Variable: Sex

Independent Variables: Survived Pclass Age SibSp Parch Fare Embarked


The accuracy of the model for predicting "Sex" for unseen data is 74.53%

Confusion matrix:
 [[ 49  49]
 [ 19 150]]


# DV - SibSp

In [79]:
my_func('SibSp')

Dependent Variable: SibSp

Independent Variables: Survived Pclass Sex Age Parch Fare Embarked


The accuracy of the model for predicting "SibSp" for unseen data is 68.91%

Confusion matrix:
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]


# DV - Parch

In [80]:
my_func('Parch')

Dependent Variable: Parch

Independent Variables: Survived Pclass Sex Age SibSp Fare Embarked


The accuracy of the model for predicting "Parch" for unseen data is 71.54%

Confusion matrix:
 [[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]


# DV - Embarked

In [81]:
my_func('Embarked')

Dependent Variable: Embarked

Independent Variables: Survived Pclass Sex Age SibSp Parch Fare


The accuracy of the model for predicting "Embarked" for unseen data is 73.41%

Confusion matrix:
 [[  0   0  49]
 [  0   0  22]
 [  0   0 196]]
